apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
  namespace: final-cluster
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: my-storage-class
  resources:
    requests:
      storage: 5Gi