version: '3.3'

services:
  django-web:
    image: bisalgt/django:v2
    build:
      context: ../.
      dockerfile: ./docker/django/Dockerfile
    ports:
      - 8000:8000
    env_file:
      - ./envfiles/.envfile.django
